### ISSUE TITLE
アバターのCSSがおかしい

### ISSUE THREAD

**Issue by calm-matsu** [calm-matsu/tec-blog#6]
以下のソースが
```CSS
.avatar {
  border-radius: 50%;
  padding: 4px;
  aspect-ratio: 1 / 1;
  width: 96px;
  height: auto;
  object-fit: cover;
  background-color: transparent;
  box-shadow: 0 0 10px rgba(0, 0, 0, 0.2);
}
```
ビルド後はこうなってしまう
```CSS
.avatar {
  border-radius:50%;
  padding:4px;
  width:96px;
  height:auto;
  aspect-ratio:1 / 1;
  -o-object-fit:cover;
  object-fit:cover;
  background-color:transparent;
  box-shadow:0 0 10px #0003
}
```
``object-fit: cover;``の指定がおかしくなっている
当然ながら、``object-fit: cover;``を消すと``-o-object-fit:cover;``だけでなく``object-fit:cover;``も消えてしまう
